export type OptionType = { value: string; label: string }

export const nifty50Symbols: OptionType[] = [
  { value: 'RELIANCE.NSE', label: 'Reliance Industries' },
  { value: 'TCS.NSE', label: 'Tata Consultancy Services' },
  { value: 'INFY.NSE', label: 'Infosys' },
  { value: 'HDFCBANK.NSE', label: 'HDFC Bank' },
  { value: 'ICICIBANK.NSE', label: 'ICICI Bank' },
  { value: 'HINDUNILVR.NSE', label: 'Hindustan Unilever' },
  { value: 'SBIN.NSE', label: 'State Bank of India' },
  { value: 'BHARTIARTL.NSE', label: 'Bharti Airtel' },
  { value: 'ITC.NSE', label: 'ITC' },
  { value: 'KOTAKBANK.NSE', label: 'Kotak Mahindra Bank' },
  { value: 'LT.NSE', label: 'Larsen & Toubro' },
  { value: 'ASIANPAINT.NSE', label: 'Asian Paints' },
  { value: 'AXISBANK.NSE', label: 'Axis Bank' },
  { value: 'BAJFINANCE.NSE', label: 'Bajaj Finance' },
  { value: 'BAJAJFINSV.NSE', label: 'Bajaj Finserv' },
  { value: 'MARUTI.NSE', label: 'Maruti Suzuki' },
  { value: 'SUNPHARMA.NSE', label: 'Sun Pharma' },
  { value: 'TITAN.NSE', label: 'Titan Company' },
  { value: 'ULTRACEMCO.NSE', label: 'UltraTech Cement' },
  { value: 'WIPRO.NSE', label: 'Wipro' },
  { value: 'POWERGRID.NSE', label: 'Power Grid Corp' },
  { value: 'NTPC.NSE', label: 'NTPC' },
  { value: 'ONGC.NSE', label: 'ONGC' },
  { value: 'JSWSTEEL.NSE', label: 'JSW Steel' },
  { value: 'TATASTEEL.NSE', label: 'Tata Steel' },
  { value: 'GRASIM.NSE', label: 'Grasim Industries' },
  { value: 'ADANIPORTS.NSE', label: 'Adani Ports' },
  { value: 'ADANIENT.NSE', label: 'Adani Enterprises' },
  { value: 'HCLTECH.NSE', label: 'HCL Technologies' },
  { value: 'TECHM.NSE', label: 'Tech Mahindra' },
  { value: 'BRITANNIA.NSE', label: 'Britannia Industries' },
  { value: 'CIPLA.NSE', label: 'Cipla' },
  { value: 'DRREDDY.NSE', label: 'Dr. Reddy’s Labs' },
  { value: 'DIVISLAB.NSE', label: 'Divi’s Laboratories' },
  { value: 'EICHERMOT.NSE', label: 'Eicher Motors' },
  { value: 'HEROMOTOCO.NSE', label: 'Hero MotoCorp' },
  { value: 'BAJAJ-AUTO.NSE', label: 'Bajaj Auto' },
  { value: 'COALINDIA.NSE', label: 'Coal India' },
  { value: 'HDFCLIFE.NSE', label: 'HDFC Life' },
  { value: 'SBILIFE.NSE', label: 'SBI Life Insurance' },
  { value: 'ICICIPRULI.NSE', label: 'ICICI Prudential Life' },
  { value: 'M&M.NSE', label: 'Mahindra & Mahindra' },
  { value: 'SHREECEM.NSE', label: 'Shree Cement' },
  { value: 'BPCL.NSE', label: 'BPCL' },
  { value: 'HINDALCO.NSE', label: 'Hindalco Industries' },
  { value: 'UPL.NSE', label: 'UPL' },
  { value: 'APOLLOHOSP.NSE', label: 'Apollo Hospitals' },
  { value: 'INDUSINDBK.NSE', label: 'IndusInd Bank' }
]
